### ISSUE TITLE
not works ??

### ISSUE THREAD

**Issue by ghost** [elbouillon/capidiem#5]
when i put capidiem . i become error (capidiem: command not found)

**Comment by elbouillon** [comment]
Hi, not capidiem does not work, I need to go back and update the code to use capifony base and add the diem features. But as I'm not a fulltime developper and I'm too busy now, I won't do that before end of the year. If you're interested in this developpment, I'd be glad to help you.

**Comment by ghost** [comment]
its ok. i can wait. and use the default symfony deploy task.

Thanks
